### PR TITLE
Cleanup file handle once reading is complete

### LINKED ISSUE #4: Full CPU usage
I've got a bit of a strange problem, this could certainly be user-error on my part, but I can't see what would be causing it at the moment. I've got a webserver written using Vapor, that runs a few shell commands with Sh on each request. This is async all the way through.

It seems that as soon as a command runs, it will try to use 100% of a core from that point onwards, as if the command returns and sits in a `while true {}` from then on. The commands _do work_, and I get valid responses... most of the time (not sure if this is related).

I've reproduced this hooked up to Xcode and I can see that the server's CPU usage is effectively zero until a command runs in Sh, at which point it's up to 400% (on a 4-core system). I can also see in Instruments that the time is mostly being spent in the closure in `PipeBuffer.init`.

Screenshot 2023-06-26 at 00 52 10

The effect of this is that any process using Sh in this way (again, might be my error!) will get slower and slower each time it does. In my case I believe Vapor is backing the serving with a thread pool that can grow to up to 32 or 64 threads or something like that, and so while things get slower with each request, it's usable until I've made enough requests to have used up all threads. At that point requests aren't processed any more.

### PR DESCRIPTION
**Pull request by danpalmer**
Fixes #4

This addresses a major usability issue that causes significant resource usage for each command run.

### CODE REVIEW

**Comment by danpalmer** [comment]
Hey @FullQueueDeveloper, just a quick follow up here. 

I think Sh is either effectively broken on the new Sonoma due to an API behaviour change, or on all macOS versions. 

Would be great to get this fix into a new release 😄

**Comment by danpalmer** [comment]
@FullQueueDeveloper Hey just a quick ping to see if this is shippable. I believe this the package is currently unusable, at least on macOS Sonoma and possibly previous versions.

**Comment by DanielSincere** [comment]
Hello @danpalmer, thanks so much for the work you put into this, I appreciate it!

**Comment by danpalmer** [comment]
Thanks!

**Pull request merged**
